### PR TITLE
Issue #75 - Adding GUI plugin to init file

### LINKED ISSUE #75: Backend Reimagining
After planning and integrating new features that touch the telemetry stream and chatting with users about toolkit functionality I've started feeling like the current backend design is lacking. Thoughts and ideas below for a potential rework of the way our backend functions. Please note, this is a massive brain dump of ideas. Thoughts and critique is definitely appreciated.

Currently our backend is divided up into two major chunks:
- `ait-gui` 
   - inbound telemetry on one or more ports. These should be binary blobs that will be unpacked into Packets
   - outbound encoded commands sent to the configured command port.

- SLE interfaces
   - Receive telemetry of some format in PDUs from RAF/RCF
   - Send commands of some format via FCLTU
   - These don't connect naturally to the Core/GUI functionality

As such, we have a bit of a gap in between the standard AIT functionality and the SLE functionality. Specifically, the telemetry stream *has* to be AIT Packets and this can be limiting depending on the setup a project needs. This works nicely if a project is dumping telemetry in a single Packet and those fit nicely in a frame (so no real "telemetry processing" is necessary), etc. 

There also isn't a convenient location to insert components that need access to the telemetry stream(s). For instance, a component that takes all telemetry and archives it to PCaps or inserts into a database needs to be "hard coded" into the pipeline. Likely the most elegant approach we can take currently is the one we took with the notification system whereby users call a function as part of their GUI bootup script to enable this on the backend. You can see the code for creating a GUI session that a greenlet monitors as part of the [notification system](https://github.com/NASA-AMMOS/AIT-GUI/blob/master/ait/gui/__init__.py#L373) as an example.

The gap between encoded command vs expected format needed by project can be overcome via extensions of `ait.core.cmd` classes while not being too onerous. However, making this more config driven could be useful, especially for different testing setups or something similar and for making it "just work" with the SLE interfaces out of the box.

---

### To the Future

I think there are two places to which we could make significant usability improvements while keeping a config / code structure that somewhat resembles our current approach.

- A generic "server" backend that supports plug-able access to the telemetry stream.
- A more robust data stream system

#### Plug-able backend

At a high level this would be changing `ait-gui` to `ait-server`. We would change the backend from "receive telemetry and send to front end / send commands to port" to a system that handles the multiplexing of telemetry streams and command output to various plugins. Plugins would implement some (to be determined) interface that allows them to receive all telemetry and send output to the server.

Imagine an example config for `ait-server` that runs plugins for:
- The GUI (which should be included by default I suppose)
- Writing telemetry to a data store
- Sending telemetry to OpenMCT

```
ait-server:
    plugins:
        - ait-gui
        - ait-datastore-writer
        - openmct-bridge

ait-datastore-writer:
    backend: InfluxDB
    username: foo
    password: bar
```

#### Stream Rework

The current stream system configures the GUI to receive a particular Packet type on a given port. There's also some flexibility for configuring if the stream is of a certain type (E.g., unsegmented CCSDS packets or the default "raw").

Creating a system where by a telemetry stream can be piped through "handlers" that perform some task on the telemetry would allow us to support customizable data flows while also providing an easy entry point for user customization.

Suppose we have a system where we receive telemetry on 3 different ports depending on the setup we're running or testing. While not necessarily realistic, hopefully it drives home the point. We'll have streams that:
- Receive "raw" telemetry specific to a type of AIT packet. This is the default that we currently have
- Receive CCSDS packets that maps apids to AIT packets. This is effectively what we currently have with `type: ccsds` and the `apid: #` attribute on packet definitions. We'll pretend this can handle segmented data even though that's not how a first pass would behave or what we currently have :)
- Receive TM Transfer frames from the SLE interface (E.g., RAF) and unpack/process as needed to get to data we can display in the UI

```
ait-server:
    plugins:
        - ait-gui
        - ait-datastore-writer
        - openmct-bridge

    inbound-streams:
        - stream:
            name: raw_ehs
            port: 3076
            handlers:
                - ait-packet-handler:
                     packet: Example_1553_EHS

        - stream:
            name: ccsds_stream
            port: 3077
            handlers:
                - ccsds-packet-handler:
                     apids:
                         1: Example_1553_EHS
                         2: Some_Other_Packet

        - stream:
            name: sle_data_stream
            port: 3078
            handlers:
                - tm-trans-frame-decode-handler
                - ccsds-packet-handler:
                     apids:
                         1: Example_1553_EHS
                         2: Some_Other_Packet

ait-datastore-writer:
    backend: InfluxDB
    username: foo
    password: bar
```

Similar to the above telemetry streams, being able to customize how we wrap encoded commands could also be useful. You could imagine an `outbound-streams` configuration option that allows you to take encoded commands, pass them through one or more handlers, and finally output them to a port. This would allow us to have different output streams with different formats so you could, for example, have an output stream that encodes as necessary to send to FSW for testing while also having a stream to encode and wrap as necessary for delivery for emission, testing with a radio, etc.

### PR DESCRIPTION
**Pull request by aywaldron**
- Replacing code in __init__.py with code for new GUI plugin.
- Removing bin/ait_gui.py (ait-gui command) since no longer relevant
with new plugin architecture

Resolves #75 along with https://github.com/NASA-AMMOS/AIT-Core/pull/140

### CODE REVIEW

**Comment by MJJoyce** [comment]
I went through and tested this with the Core server changes. Still need to poke further at the sequence/script/command handling and make sure that's working as expected. I opened a few tickets in core to address issue that I ran into when testing and I've pushed an update commit to the branch for issue-75 as well.

NASA-AMMOS/AIT-Core#146
NASA-AMMOS/AIT-Core#147
NASA-AMMOS/AIT-Core#148

We need to update the way that we're passing log/telemetry stream information into the GUI. At the moment the stream names are hardcoded and that's not going to last an encounter with a user and a mildly different use case than our default one.

**Comment by MJJoyce** [comment]
Update after some testing:
- [X] Test Command functionality. Ensure output from server matches old output
Tested command output by capturing stream output at the port. Did a hexdump and recreated a Cmd object from the message. This required a small change to the port output client. I'll open a PR for the changes shortly.

- [X] Test Sequence functionality. Ensure output from server matches old output
The sequence script is still writing directly to a port instead of to a ZMQ port for integration into the new server. This will need to change in Core but at the very least the functionality still works as is (i.e., no regressions with the new Plugin).

- [X] Test Script functionality. Ensure output from server matches old output
Scripts functioned as expected. Like sequences, this requires CmdAPI updates to core to be truly integrated with the new server but it didn't regress with the new plugin.

- [X] Logs aren't showing in the UI. We need to debug / fix this
The example config in Core specifies the log_stream port as a different one from what we expect. I'll throw a PR up with changes.

- [ ] Stream names for log/telemetry are hardcoded. This needs to be configurable.

**Comment by aywaldron** [comment]
@MJJoyce and I discussed the last check box above and decided to check for custom GUI plugin params "log_stream_names" and "telem_stream_names" (lists) to manage in the GUI plugin (these names would have to be duplicated in the plugin `inputs` param). If those keys don't exist, the GUI would default the names to "log_stream" and "telem_stream" which are the defaults in the config as well.

**Comment by aywaldron** [comment]
Merging per @MJJoyce

**Pull request merged**
