### PR TITLE
Make end time match expected format (#143)

### LINKED ISSUE #143: End time in search for playback range not expected format
This line throws an error because `end_time` does not match the expected format:
https://github.com/NASA-AMMOS/AIT-GUI/blob/bff6cd7b97c305a8f2efe401e0369aa8d1d6eef4/ait/gui/__init__.py#L1082

To replicate: 
1. Check out branch [issue-142](https://github.com/NASA-AMMOS/AIT-GUI/tree/issue-142) and use latest updated master branch of AIT-Core
2. Update config.yaml to contain the following:
> ```     
> plugins:
>     - plugin:
>          name: ait.gui.AITGUIPlugin
>          inputs:
>               - telem_stream
>               - log_stream
>          outputs:
>               - command_stream
>
>     - plugin:
>          name: ait.core.server.plugins.DataArchive
>          datastore: ait.core.db.InfluxDBBackend
>          inputs:
>              - telem_stream
> ```
3. Run `ait-server` and navigate to localhost:8080
4. Run `ait-example`

### PR DESCRIPTION
**Pull request by aywaldron**
#142 should be merged first. This branch has been rebased with changes in #142.

To test this fix works, check out this branch and follow steps 2-4 outlined in #143 .

Resolves #143

### CODE REVIEW

**Comment by aywaldron** [comment]
Updating per @MJJoyce 's comment on #147

**Comment by MJJoyce** [comment]
Hey @aywaldron,

I might be misunderstand the recent changes pushed here but I think it's doing something extra than was chatted about on [the other ticket](https://github.com/NASA-AMMOS/AIT-GUI/pull/147#issuecomment-550001636).

```
second = int(round(float(time_split[1][:-1]) / 10**9))
```

All of this conversion aside, should the value of this (assuming the original value is in nanoseconds) always give us a fractional number? Or said differently, we're splitting the fractional seconds off and then adding some offset to encompass the fractional time. That fractional time is always going to be at most 1 second so why not round the way mentioned in the other ticket? Specifically, split on `.` and then add 1 second to the end time.

I think we could really simply both the start and end time code here to be in line with what's mentioned in the other ticket. Start time would split on `.` and add no offset. End times would split on `.` and add a 1 second offset.

Thoughts? Am I not understanding something above?

**Comment by aywaldron** [comment]
@MJJoyce it is determining whether the second should be rounded up or down rather than always rounding up. That line of code will give you either 0 or 1 depending on the value of the nanoseconds, so its more accurate than always rounding up.

**Comment by aywaldron** [comment]
Per discussion with @MJJoyce , updating to always round up for end time and round down for start time to encapsulate the correct time range.

**Pull request merged**
